/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alvaro.interfaces.vuelos2;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author alvarobs
 */
public class Company extends javax.swing.JFrame {
    
    ModeloTablaCompany modelo = new ModeloTablaCompany();

    /**
     * Creates new form Company
     */
    public Company() {
        initComponents();
        verVuelos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnEditor = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl.setModel(modelo);
        jScrollPane1.setViewportView(tbl);

        btnAlta.setText("Dar de alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnEditor.setText("Editar");

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(btnAlta)
                .addGap(242, 242, 242)
                .addComponent(btnBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditor)
                .addGap(130, 130, 130)
                .addComponent(volver)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja)
                    .addComponent(btnEditor)
                    .addComponent(volver))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDarDeAlta().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDarDeBaja().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_btnBajaActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Company().setVisible(true);
               
            }
        });
    }
    public static List<String[]> readCSV() {
        List<String[]> data = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader("src/main/java/archivos/companyCSV.csv"))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Dividir la línea por comas para obtener los datos individuales
                String[] row = line.split(",");
                data.add(row);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        return data;
    }
    public static ArrayList<CompanyObjeto> leerLista(){
        
          ArrayList<CompanyObjeto> listaCompany = new ArrayList<>();
          try (BufferedReader br = new BufferedReader(new FileReader("src/main/java/archivos/companyCSV.csv"))) {
            String line;
            while ((line = br.readLine()) != null) {
                 CompanyObjeto co=new CompanyObjeto();
                // Dividir la línea por comas para obtener los datos individuales
                String[] row = line.split(",");
                String prefijo=row[0];
                String codigo=row[1];
                String nombre=row[2];
                String direccion=row[3];
                String municipio=row[4];
                String tlfPasajero=row[5];
                String tlfAereopuerto=row[6];
                int prefijoInt=Integer.parseInt(prefijo);
                co.setPrefijo(prefijoInt);
                co.setCodigo(codigo);
                co.setNombre(nombre);
                co.setDireccion(direccion);
                co.setMunicipio(municipio);
                co.setTelefonoInfoPasajer(tlfPasajero);
                co.setTelefonoInfoAereopuerto(tlfAereopuerto);
                listaCompany.add(co);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
         return listaCompany;
    }
    public void verVuelos(){
        ArrayList<CompanyObjeto> lista=leerLista();
        modelo.setRowCount(lista.size());
        int f=0;
        for(CompanyObjeto co:lista){
            tbl.getModel().setValueAt(co.getPrefijo(),f,0);
            tbl.getModel().setValueAt(co.getCodigo(),f,1);
            tbl.getModel().setValueAt(co.getNombre(),f,2);
            tbl.getModel().setValueAt(co.getDireccion(),f,3);
            tbl.getModel().setValueAt(co.getMunicipio(),f,4);
            tbl.getModel().setValueAt(co.getTelefonoInfoPasajer(),f,5);
            tbl.getModel().setValueAt(co.getTelefonoInfoAereopuerto(),f,6);
            f++;
        }
          
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnEditor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
