/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alvaro.interfaces.vuelos2;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author alvarobs
 */
public class FrmDarDeBaja extends javax.swing.JFrame {

    /**
     * Creates new form FrmDarDeBaja
     */
    public FrmDarDeBaja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPrefijo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnDarDeBaja = new javax.swing.JButton();
        lblPrefijoError = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Prefijo:");

        txtPrefijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrefijoActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo:");

        btnDarDeBaja.setText("Dar de baja");
        btnDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarDeBajaActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDarDeBaja)
                                .addGap(97, 97, 97)
                                .addComponent(btnVolver))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(100, 100, 100))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(txtPrefijo))
                                .addGap(18, 18, 18)
                                .addComponent(lblPrefijoError, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrefijoError))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDarDeBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrefijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrefijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrefijoActionPerformed

    private void btnDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarDeBajaActionPerformed
        darDeBaja();
    }//GEN-LAST:event_btnDarDeBajaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDarDeBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDarDeBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDarDeBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDarDeBaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDarDeBaja().setVisible(true);
            }
        });
    }

    public void darDeBaja() {
        ArrayList<CompanyObjeto> lista = Company.leerLista();
        ArrayList<CompanyObjeto> lista2=new ArrayList<>();
        int prefijoInt=0;
        String prefijo=txtPrefijo.getText();
        prefijoInt=Integer.parseInt(prefijo);
        String codigo=txtCodigo.getText();
       boolean comp=comprobarExiste();
       if(comp){
       for(CompanyObjeto co:lista){
           if((co.getPrefijo()==prefijoInt) && (co.getCodigo().equals(codigo))){
               
           }else{
               int prefijo2=co.getPrefijo();
               String codigo2=co.getCodigo();
               String nombre=co.getNombre();
               String direccion=co.getDireccion();
               String municipio=co.getMunicipio();
               String tlfPasajero=co.getTelefonoInfoPasajer();
               String tlfAereopuerto=co.getTelefonoInfoAereopuerto();
               lista2.add(co);
           }
       }
       String ruta="src/main/java/archivos/companyCSV.csv";
       reescribirCSV(lista2,ruta);
       lblInfo.setText("Se ha actualizado el archivo");
       }else{
           lblError.setText("No existe");
        }
        }
    public boolean comprobarExiste(){
       
       ArrayList<CompanyObjeto> lista = Company.leerLista();
        for (CompanyObjeto co : lista) {
            int prefijoInt = 0;
            String prefijo = txtPrefijo.getText();
            if (!FrmDarDeAlta.esNumeroEntero(prefijo)) {
                lblPrefijoError.setText("Tiene que ser un numero");
                lblInfo.setText("");
            } else {
                lblPrefijoError.setText("");
                prefijoInt = Integer.parseInt(prefijo);
                String codigo = txtCodigo.getText();
                if((co.getPrefijo()==prefijoInt) && (co.getCodigo().equals(codigo))){
                    lblError.setText("");
                    lblInfo.setText("");
                    return true;
                }
                }
        }
        return false;
    }
     public static void reescribirCSV(ArrayList<CompanyObjeto> listaObjetos, String rutaArchivo) {
        try (FileWriter writer = new FileWriter(rutaArchivo)) {
            for (CompanyObjeto objeto : listaObjetos) {
                // Adaptar los campos del objeto a una cadena CSV
                String csvLine = objeto.getPrefijo() + "," + objeto.getCodigo() + "," + objeto.getNombre() + ","
                        + objeto.getDireccion() + "," + objeto.getMunicipio() + "," + objeto.getTelefonoInfoPasajer()
                        + "," + objeto.getTelefonoInfoAereopuerto() + "\n";

                // Escribir la línea CSV en el archivo
                writer.write(csvLine);
            }

            System.out.println("Objetos guardados en formato CSV en " + rutaArchivo);
        } catch (IOException e) {
            e.printStackTrace();
        }
     }
            
    
        /**
         * public static void leerCSV(){ try (BufferedReader br = new
         * BufferedReader(new FileReader(rutaArchivo))) { // Leer todas las
         * líneas del archivo y almacenarlas en la lista String linea; while
         * ((linea = br.readLine()) != null) { // Si la línea no contiene el
         * objeto que se va a eliminar, agrégala a la lista
         *
         * }
         * } catch (IOException e) { e.printStackTrace(); return; }
    }
         */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDarDeBaja;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblPrefijoError;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPrefijo;
    // End of variables declaration//GEN-END:variables
}
