/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alvaro.interfaces.vuelos2;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author usuario
 */
public class GestionVuelos extends javax.swing.JFrame {

    ModeloTablaVuelos modelo = new ModeloTablaVuelos();

    /**
     * Creates new form GestionVuelos
     */
    public GestionVuelos() {
        initComponents();
        verVuelos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnDarDeAlta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnDarDeBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl.setModel(modelo);
        jScrollPane1.setViewportView(tbl);

        btnDarDeAlta.setText("Dar de alta");
        btnDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarDeAltaActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnDarDeBaja.setText("Dar de baja");
        btnDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarDeBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 381, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnDarDeAlta)
                .addGap(40, 40, 40)
                .addComponent(btnDarDeBaja)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDarDeAlta)
                    .addComponent(btnVolver)
                    .addComponent(btnDarDeBaja))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarDeAltaActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DarDeAltaVuelos().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnDarDeAltaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarDeBajaActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DarDeBajaVuelos().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnDarDeBajaActionPerformed
    public static List<String[]> readCSV() {
        List<String[]> data = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader("src/main/java/archivos/vuelos.csv"))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Dividir la línea por comas para obtener los datos individuales
                String[] row = line.split(",");
                data.add(row);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        return data;
    }

    public static ArrayList<Vuelo> leerLista() {
        ArrayList<Vuelo> lista = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("src/main/java/archivos/vuelos.csv"))) {
            String line;
            while ((line = br.readLine()) != null) {
                Vuelo co = new Vuelo();
                // Dividir la línea por comas para obtener los datos individuales
                String[] row = line.split(",");
                String codigoVuelo = row[0];
                String numeroPlazas = row[1];
                String horaSalida = row[2];
                String horaLlegada = row[3];
                String diasOperacion = row[4];
                String codigoAereopuertoOrigen = row[5];
                String codigoAereopuertoDestino = row[6];

                int intNumeroPlazas = Integer.parseInt(numeroPlazas);
                co.setCodigoVuelo(codigoVuelo);
                co.setNumeroPlazas(intNumeroPlazas);
                String dateHoraSalida = horaSalida;
                String dateHoraLlegada = horaLlegada;
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");

                //Date date = null;
                // Date date2 = null;
                LocalTime localHoraSalida = null;
                LocalTime localHoraLlegada = null;

                localHoraSalida = LocalTime.parse(dateHoraSalida, formatter);
                localHoraLlegada = LocalTime.parse(dateHoraLlegada, formatter);

                co.setHoraSalida(localHoraSalida);
                co.setHoraLlegada(localHoraLlegada);
                co.setDiasOperacion(diasOperacion);
                co.setCodigoAereopuertoOrigen(codigoAereopuertoOrigen);
                co.setCodigoAereopuertoDestino(codigoAereopuertoDestino);
                lista.add(co);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return lista;
    }

    public void verVuelos() {
        ArrayList<Vuelo> lista = leerLista();
        modelo.setRowCount(lista.size());
        int f = 0;
        for (Vuelo co : lista) {
            tbl.getModel().setValueAt(co.getCodigoVuelo(), f, 0);
            tbl.getModel().setValueAt(co.getNumeroPlazas(), f, 1);
            tbl.getModel().setValueAt(co.getHoraSalida(), f, 2);
            tbl.getModel().setValueAt(co.getHoraLlegada(), f, 3);
            tbl.getModel().setValueAt(co.getDiasOperacion(), f, 4);
            tbl.getModel().setValueAt(co.getCodigoAereopuertoOrigen(), f, 5);
            tbl.getModel().setValueAt(co.getCodigoAereopuertoDestino(), f, 6);
            f++;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDarDeAlta;
    private javax.swing.JButton btnDarDeBaja;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
